site_name: documented
repo_url: https://github.com/anatoly-scherbakov/documented
repo_name: documented
copyright: Copyright &copy; 2023 <a href="https://yeti.sh">Anatoly Scherbakov</a>

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        python:
          options: {}
  - macros:
      on_error_fail: true
      modules:
        - macros

theme:
  name: material
  logo: images/quotes.svg
  features:
    - navigation.sections
    - content.code.annotate
  prev_next_buttons_location: bottom

extra_css:
  - css/custom.css
